###
POST http://localhost:9000/api/clientes HTTP/1.1
Content-Type: application/json

{
    "id": null,
    "nombre": "Pepe",
    "edad": "30",
    "direccion": "Calle 1",
    "telefono": "1234567890"
}

###
PUT http://localhost:9000/api/clientes/657a3a855823ad88afcd1d73 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Pepe nuevo",
    "edad": "100",
    "direccion": "Calle 1000",
    "telefono": "999"
}
###
GET http://localhost:9000/api/clientes HTTP/1.1

###
DELETE  http://localhost:9000/api/clientes/657a3a7c5823ad88afcd1d70 HTTP/1.1

