###
POST http://localhost:9000/api/presupuestos HTTP/1.1
Content-Type: application/json

{
    "visitaId": "657b2545bce73ec451298f95",
    "tipo": "contado",
    "cantidad": "40000"
}

###
GET http://localhost:9000/api/visitas HTTP/1.1


###
GET http://localhost:9000/api/presupuestos HTTP/1.1